In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline    
from sklearn.model_selection import train_test_split
from numpy import mean
from numpy import std

# **Datasets Reading** 

In [2]:
# x_train = pd.read_csv('Datasets/X_Train With Yeo Johnson 80-20.csv')

# x_test = pd.read_csv('Datasets/X_Test With Yeo Johnson 80-20.csv')

# y_train = pd.read_csv('Datasets/Y_Train With Yeo Johnson 80-20.csv')

# y_test = pd.read_csv('Datasets/Y_Test With Yeo Johnson 80-20.csv')

In [3]:
x_train = pd.read_csv('../Updated Datasets/Update X_Train With Yeo Johnson 80-20.csv')

x_test = pd.read_csv('../Updated Datasets/Update X_Test With Yeo Johnson 80-20.csv')

y_train = pd.read_csv('../Updated Datasets/Update Y_Train With Yeo Johnson 80-20.csv')

y_test = pd.read_csv('../Updated Datasets/Update Y_Test With Yeo Johnson 80-20.csv')

In [4]:
x_train

Gender       AGE      Urea        Cr     HbA1c      Chol        TG  \
0    0.913664 -0.150582 -0.981792  0.341858 -0.229612 -0.809727  0.534238   
1    0.913664  0.783528  0.183564 -0.031784  0.407443 -0.809727  1.793247   
2   -1.094494 -0.789545 -1.733109 -0.767442 -0.802594 -1.337042 -1.076857   
3   -1.094494  0.458721  2.146976  2.152073 -0.088168 -0.223456  0.880348   
4    0.913664 -0.876228  0.452568 -0.066956 -0.278232  0.093852  1.851639   
..        ...       ...       ...       ...       ...       ...       ...   
206 -1.094494 -0.053378  0.582251  0.653076 -1.329668 -0.062941 -0.910703   
207 -1.094494 -0.613164 -0.415121 -1.443545 -1.148477  0.543163 -0.061015   
208  0.913664  0.783528  2.146976  2.160081  0.933351  1.445078  0.880348   
209 -1.094494  0.458721  0.670368  1.530827  0.214670 -0.470402  0.451731   
210  0.913664  0.565679  2.146976  2.160081  0.903548  0.015947  0.165510   

          HDL       LDL      VLDL       BMI  
0    1.509378 -1.591336 -0.824577 -0.484974  
1   -0.681912  0.022661  0.008711  0.729984  
2   -0.037930 -1.223476  0.877448 -1.288259  
3   -2.801192  0.226574  0.746810  0.383017  
4   -0.681912 -0.866209  1.614820 -1.288259  
..        ...       ...       ...       ...  
206  1.365324  1.501711  0.597015 -1.007826  
207 -0.681912  1.069106  0.008711 -0.244194  
208 -0.037930  1.669644  0.746810  1.185392  
209 -0.343819 -0.520904  0.229703  1.185392  
210  0.233455  0.022661  0.008711  1.458732  

[211 rows x 11 columns]

In [5]:
print(y_train['Class'].value_counts())

2    108
0     71
1     32
Name: Class, dtype: int64


# Backward Feature Elimination using Logistic Regression

In [6]:
# from mlxtend.feature_selection import SequentialFeatureSelector as sfs
# from sklearn.linear_model import LogisticRegression

# lreg = LogisticRegression()
# sfs1 = sfs(lreg, k_features=10, forward=False, verbose=1, scoring='neg_mean_squared_error')
# sfs1 = sfs1.fit(x_train, y_train)

In [7]:
# feat_names = list(sfs1.k_feature_names_)
# print(feat_names)

In [8]:
BFE_Top_4_X = x_train[['AGE', 'Urea', 'Cr', 'HbA1c']]
BFE_Top_5_X = x_train[['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol']]
BFE_Top_7_X = x_train[['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL']]
BFE_Top_9_X = x_train[['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL']]
x_train = BFE_Top_9_X

In [9]:
BFE_Top_4_X = x_test[['AGE', 'Urea', 'Cr', 'HbA1c']]
BFE_Top_5_X = x_test[['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol']]
BFE_Top_7_X = x_test[['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL']]
BFE_Top_9_X = x_test[['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL']]
x_test = BFE_Top_9_X

In [10]:
metrics = ["Accuracy", "Precision", "Recall", "F1 Score", "Cohen Kappa", "AUC"]

performance_dict = {}
performance_dict['Metrics'] = metrics

In [11]:
metrics_grid = ["Accuracy", "Precision", "Recall", "F1 Score", "Cohen Kappa", "AUC"]

performance_dict_grid = {}
performance_dict_grid['Metrics'] = metrics_grid

# SMOTETomek Balancing

In [12]:

# from collections import Counter
# from imblearn.combine import SMOTETomek
# counter = Counter(y_train)
# print('Before', counter)
# smtt = SMOTETomek(random_state = 139)
# x_train_smt, y_train_smt = smtt.fit_resample(x_train, y_train)
# counter = Counter(y_train_smt)
# print('After', counter)


In [13]:

# from collections import Counter
# from imblearn.combine import SMOTETomek
# counter = Counter(y_test)
# print('Before', counter)
# smtt = SMOTETomek(random_state = 139)
# x_test_smt, y_test_smt = smtt.fit_resample(x_test, y_test)
# counter = Counter(y_test_smt)
# print('After', counter)


# Support Vector Classifier Train, Test 

In [14]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
modelSVC = SVC(probability=True)
modelSVC.fit(x_train, y_train)
#modelSVC.fit(x_test, y_test)
#print(modelSVC.score(x_test, y_test))

y_pred_svc = modelSVC.predict(x_test)
#y_pred = modelSVC.predict(x_train)
svc_acc = accuracy_score(y_test, y_pred_svc)
#ac = accuracy_score(y_train, y_pred)
print(svc_acc)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))

0.9245283018867925
[[24  1  0]
 [ 0  5  3]
 [ 0  0 20]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        25
           1       0.83      0.62      0.71         8
           2       0.87      1.00      0.93        20

    accuracy                           0.92        53
   macro avg       0.90      0.86      0.87        53
weighted avg       0.93      0.92      0.92        53



C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
from sklearn.metrics import cohen_kappa_score, f1_score, precision_score, recall_score, roc_auc_score

cmSVC = confusion_matrix(y_test, modelSVC.predict(x_test))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmSVC[1,1]  
TN = cmSVC[0,0] 
FP = cmSVC[0,1] 
FN = cmSVC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
totalSVC=sum(sum(cmSVC))
Accuracy = (TN+TP)/totalSVC
# MCC
val = (TP * TN) - (FP * FN)
MCC_SVC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))



Y_pred_svc = modelSVC.predict(x_test)


cohen_score = cohen_kappa_score(y_test, Y_pred_svc)
f1 = f1_score(y_test, Y_pred_svc, average = "weighted")
precision = precision_score(y_test, Y_pred_svc, average = "weighted")
recall = recall_score(y_test, Y_pred_svc, average = "weighted")

pred_prob = modelSVC.predict_proba(x_test)
auc_score = roc_auc_score(y_test, pred_prob, multi_class='ovr')

print(f"Precision  {precision}")
print(f"f1 Score  {f1}")
print(f"Recall  {recall}")
specificity = TNR
print("Specificity/TNR: " + str(TNR))
print("Cohen Kappa: " + str(cohen_score))
print(f"AUC Score  {auc_score}")

Precision  0.9256220946130708
f1 Score  0.920919486706486
Recall  0.9245283018867925
Specificity/TNR: 0.96
Cohen Kappa: 0.8753674309229865
AUC Score  0.9799663299663299


In [16]:
svc_performances = [svc_acc, precision, recall, f1, cohen_score, auc_score ]
performance_dict['SVC'] = svc_performances

performance_dict

{'Metrics': ['Accuracy',
  'Precision',
  'Recall',
  'F1 Score',
  'Cohen Kappa',
  'AUC'],
 'SVC': [0.9245283018867925,
  0.9256220946130708,
  0.9245283018867925,
  0.920919486706486,
  0.8753674309229865,
  0.9799663299663299]}

# Supper Vector Classifier Hyperparameter Tuning GridSearchCV

In [17]:
from sklearn.model_selection import GridSearchCV
GSCV_SVC = GridSearchCV(modelSVC,{
    'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel':['rbf', 'linear', 'poly', 'sigmoid']
}, 
cv = 10, 
return_train_score = False
)
GSCV_SVC.fit(x_train, y_train)
GSCV_SVC.cv_results_

C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

{'mean_fit_time': array([0.02623174, 0.01266863, 0.01286476, 0.01353602, 0.01485529,
        0.01276727, 0.01186535, 0.01176276, 0.01546016, 0.01315897,
        0.01103795, 0.01924767, 0.02014551, 0.01585677, 0.01495883,
        0.01555769, 0.01854479, 0.01375301, 0.01106551, 0.01605647,
        0.02582695, 0.01475983, 0.01343381, 0.0134582 , 0.01505892,
        0.01646283, 0.01225822, 0.01167138, 0.01544316, 0.01435797,
        0.01192341, 0.01435828, 0.0183521 , 0.01755493, 0.01057563,
        0.01475999, 0.01895175, 0.01715412, 0.01525869, 0.02044382,
        0.03490543, 0.0244328 , 0.0169534 , 0.01565735, 0.02074418,
        0.02313771, 0.01874943, 0.01047115, 0.01785433, 0.03051789,
        0.02293859, 0.01994531, 0.027526  , 0.02592986, 0.02174151,
        0.02832398, 0.02991931, 0.02762513, 0.0186496 , 0.02383554,
        0.03799772, 0.02194054, 0.01406162, 0.01485956, 0.01725349,
        0.02553108, 0.01575699, 0.01316364, 0.01605656, 0.02433469,
        0.0168514 , 0.01445982,

In [18]:
df_svc_grid = pd.DataFrame(GSCV_SVC.cv_results_)
df_svc_grid

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.026232      0.003421         0.002588        0.000906       1   
1         0.012669      0.001620         0.001998        0.000446       1   
2         0.012865      0.001917         0.001698        0.000459       1   
3         0.013536      0.001551         0.002197        0.000404       1   
4         0.014855      0.002068         0.002097        0.000298       1   
..             ...           ...              ...             ...     ...   
395       0.014062      0.001044         0.001896        0.000537      20   
396       0.019447      0.003162         0.002095        0.000300      20   
397       0.065524      0.016836         0.001796        0.000399      20   
398       0.013754      0.002308         0.002400        0.000666      20   
399       0.018949      0.002891         0.001995        0.000631      20   

    param_gamma param_kernel                                           params  \
0             1          rbf            {'C': 1, 'gamma': 1, 'kernel': 'rbf'}   
1             1       linear         {'C': 1, 'gamma': 1, 'kernel': 'linear'}   
2             1         poly           {'C': 1, 'gamma': 1, 'kernel': 'poly'}   
3             1      sigmoid        {'C': 1, 'gamma': 1, 'kernel': 'sigmoid'}   
4           0.1          rbf          {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}   
..          ...          ...                                              ...   
395       0.001      sigmoid   {'C': 20, 'gamma': 0.001, 'kernel': 'sigmoid'}   
396      0.0001          rbf      {'C': 20, 'gamma': 0.0001, 'kernel': 'rbf'}   
397      0.0001       linear   {'C': 20, 'gamma': 0.0001, 'kernel': 'linear'}   
398      0.0001         poly     {'C': 20, 'gamma': 0.0001, 'kernel': 'poly'}   
399      0.0001      sigmoid  {'C': 20, 'gamma': 0.0001, 'kernel': 'sigmoid'}   

     split0_test_score  split1_test_score  ...  split3_test_score  \
0             0.590909           0.761905  ...           0.619048   
1             0.818182           0.857143  ...           0.904762   
2             0.727273           0.809524  ...           0.714286   
3             0.681818           0.761905  ...           0.809524   
4             0.772727           0.904762  ...           0.952381   
..                 ...                ...  ...                ...   
395           0.727273           0.761905  ...           0.857143   
396           0.681818           0.761905  ...           0.857143   
397           0.863636           0.952381  ...           0.952381   
398           0.454545           0.476190  ...           0.523810   
399           0.454545           0.523810  ...           0.523810   

     split4_test_score  split5_test_score  split6_test_score  \
0             0.761905           0.619048           0.714286   
1             0.952381           0.761905           0.952381   
2             0.714286           0.761905           0.857143   
3             0.904762           0.619048           0.904762   
4             0.904762           0.714286           0.857143   
..                 ...                ...                ...   
395           0.857143           0.619048           0.809524   
396           0.809524           0.619048           0.761905   
397           1.000000           0.666667           0.952381   
398           0.523810           0.523810           0.523810   
399           0.523810           0.523810           0.523810   

     split7_test_score  split8_test_score  split9_test_score  mean_test_score  \
0             0.619048           0.761905           0.619048         0.673377   
1             0.857143           0.904762           0.857143         0.872294   
2             0.714286           0.952381           0.857143         0.787013   
3             0.666667           0.761905           0.571429         0.744372   
4             0.809524           0.857143           0.857143         0.853463   
..                 ... 

In [19]:
df_svc_grid[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0         1          rbf         0.673377
1         1       linear         0.872294
2         1         poly         0.787013
3         1      sigmoid         0.744372
4         1          rbf         0.853463
..      ...          ...              ...
395      20      sigmoid         0.787013
396      20          rbf         0.763420
397      20       linear         0.891126
398      20         poly         0.512121
399      20      sigmoid         0.516883

[400 rows x 3 columns]

In [20]:
print(GSCV_SVC.best_score_)
gscv_svc_acc = GSCV_SVC.best_score_
print(GSCV_SVC.best_params_)

0.9101731601731602
{'C': 7, 'gamma': 1, 'kernel': 'linear'}


In [21]:
grid_predictions = GSCV_SVC.predict(x_test)

# print classification report
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        25
           1       0.75      0.75      0.75         8
           2       1.00      1.00      1.00        20

    accuracy                           0.92        53
   macro avg       0.89      0.89      0.89        53
weighted avg       0.92      0.92      0.92        53



In [22]:
from sklearn.metrics import cohen_kappa_score, f1_score, precision_score, recall_score, roc_auc_score

cmSVC = confusion_matrix(y_test, GSCV_SVC.predict(x_test))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmSVC[1,1]  
TN = cmSVC[0,0] 
FP = cmSVC[0,1] 
FN = cmSVC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
totalSVC=sum(sum(cmSVC))
Accuracy = (TN+TP)/totalSVC
# MCC
val = (TP * TN) - (FP * FN)
MCC_SVC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))



y_pred_svc_grid = GSCV_SVC.predict(x_test)


cohen_score = cohen_kappa_score(y_test, y_pred_svc_grid)
f1 = f1_score(y_test, y_pred_svc_grid, average = "weighted")
precision = precision_score(y_test, y_pred_svc_grid, average = "weighted")
recall = recall_score(y_test, y_pred_svc_grid, average = "weighted")

pred_prob = GSCV_SVC.predict_proba(x_test)
auc_score = roc_auc_score(y_test, pred_prob, multi_class='ovr')

print(f"Precision  {precision}")
print(f"f1 Score  {f1}")
print(f"Recall  {recall}")
specificity = TNR
print("Specificity/TNR: " + str(TNR))
print("Cohen Kappa: " + str(cohen_score))
print(f"AUC Score  {auc_score}")

Precision  0.9245283018867925
f1 Score  0.9245283018867925
Recall  0.9245283018867925
Specificity/TNR: 0.92
Cohen Kappa: 0.8767441860465116
AUC Score  0.987037037037037


In [23]:
svc_performances_grid = [gscv_svc_acc, precision, recall, f1, cohen_score, auc_score ]
performance_dict_grid['SVC'] = svc_performances_grid

performance_dict_grid

{'Metrics': ['Accuracy',
  'Precision',
  'Recall',
  'F1 Score',
  'Cohen Kappa',
  'AUC'],
 'SVC': [0.9101731601731602,
  0.9245283018867925,
  0.9245283018867925,
  0.9245283018867925,
  0.8767441860465116,
  0.987037037037037]}

# Logistic Regression Train, Test

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelLR = LogisticRegression()
modelLR.fit(x_train, y_train)

y_pred_lr = modelLR.predict(x_test)
lr_ac = accuracy_score(y_test, y_pred_lr)

print("Training Accuracy: {:.3f}".format(modelLR.score(x_train, y_train)))
print("Testing Accuracy: {:.3f}".format(modelLR.score(x_test, y_test)))

print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

Training Accuracy: 0.867
Testing Accuracy: 0.830
[[23  2  0]
 [ 1  2  5]
 [ 0  1 19]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94        25
           1       0.40      0.25      0.31         8
           2       0.79      0.95      0.86        20

    accuracy                           0.83        53
   macro avg       0.72      0.71      0.70        53
weighted avg       0.81      0.83      0.82        53



C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test, modelLR.predict(x_test))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred_lr = modelLR.predict(x_test)
pred_prob = modelLR.predict_proba(x_test)


cohen_score = cohen_kappa_score(y_test, Y_pred_lr)
f1 = f1_score(y_test, Y_pred_lr, average = "weighted")
precision = precision_score(y_test, Y_pred_lr, average = "weighted")
recall = recall_score(y_test, Y_pred_lr, average = "weighted")


auc_score = roc_auc_score(y_test, pred_prob, multi_class='ovr')

print(f"Precision  {precision}")
print(f"f1 Score  {f1}")
print(f"Recall  {recall}")
specificity = TNR
print("Specificity/TNR: " + str(TNR))

print("Cohen Kappa: " + str(cohen_score))
print(f"AUC Score  {auc_score}")

Precision  0.8111635220125786
f1 Score  0.8151632733842975
Recall  0.8301886792452831
Specificity/TNR: 0.92
Cohen Kappa: 0.7175843694493783
AUC Score  0.9544083694083693


In [26]:
rfc_performances = [lr_ac, precision, recall, f1, cohen_score, auc_score ]
performance_dict['LR'] = rfc_performances

performance_dict

{'Metrics': ['Accuracy',
  'Precision',
  'Recall',
  'F1 Score',
  'Cohen Kappa',
  'AUC'],
 'SVC': [0.9245283018867925,
  0.9256220946130708,
  0.9245283018867925,
  0.920919486706486,
  0.8753674309229865,
  0.9799663299663299],
 'LR': [0.8301886792452831,
  0.8111635220125786,
  0.8301886792452831,
  0.8151632733842975,
  0.7175843694493783,
  0.9544083694083693]}

# Logistic Regression Hyperparameter Tuning GridSearchCV

In [27]:
from sklearn import linear_model

C = np.logspace(0, 4, 10)
penalty = ['l1', 'l2']
solver = ['liblinear', 'saga']
hyperparameters = dict(C=C, penalty=penalty, solver=solver)
logistic = linear_model.LogisticRegression()
GSCV_LR = GridSearchCV(logistic, hyperparameters, cv = 10)
GSCV_LR.fit(x_train, y_train)
GSCV_LR.cv_results_

C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\babar\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

{'mean_fit_time': array([0.00408816, 0.01485953, 0.00408874, 0.00648139, 0.00418863,
        0.01745234, 0.00358982, 0.00847681, 0.00448771, 0.01974683,
        0.00488727, 0.01216555, 0.0048856 , 0.01945081, 0.0050858 ,
        0.01336343, 0.00438712, 0.01715376, 0.00408826, 0.01097016,
        0.00388887, 0.01505573, 0.00349228, 0.01127055, 0.00369167,
        0.01505325, 0.00389259, 0.0100698 , 0.00419407, 0.01535702,
        0.00329697, 0.01157629, 0.00399196, 0.0168467 , 0.00339313,
        0.01226389, 0.00389709, 0.01735079, 0.00339375, 0.01147087]),
 'std_fit_time': array([0.00094086, 0.0030732 , 0.00121713, 0.00092009, 0.00086944,
        0.00343332, 0.00079752, 0.00215081, 0.00066885, 0.00367311,
        0.00029856, 0.0028141 , 0.00082814, 0.0034645 , 0.00069808,
        0.00282852, 0.00091423, 0.00217643, 0.00082908, 0.00183893,
        0.00069764, 0.0020744 , 0.00066749, 0.0020494 , 0.00064391,
        0.00129128, 0.00069822, 0.00150347, 0.00040332, 0.00279785,
        0.000

In [28]:
df_lr_grid = pd.DataFrame(GSCV_SVC.cv_results_)
df_lr_grid

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.026232      0.003421         0.002588        0.000906       1   
1         0.012669      0.001620         0.001998        0.000446       1   
2         0.012865      0.001917         0.001698        0.000459       1   
3         0.013536      0.001551         0.002197        0.000404       1   
4         0.014855      0.002068         0.002097        0.000298       1   
..             ...           ...              ...             ...     ...   
395       0.014062      0.001044         0.001896        0.000537      20   
396       0.019447      0.003162         0.002095        0.000300      20   
397       0.065524      0.016836         0.001796        0.000399      20   
398       0.013754      0.002308         0.002400        0.000666      20   
399       0.018949      0.002891         0.001995        0.000631      20   

    param_gamma param_kernel                                           params  \
0             1          rbf            {'C': 1, 'gamma': 1, 'kernel': 'rbf'}   
1             1       linear         {'C': 1, 'gamma': 1, 'kernel': 'linear'}   
2             1         poly           {'C': 1, 'gamma': 1, 'kernel': 'poly'}   
3             1      sigmoid        {'C': 1, 'gamma': 1, 'kernel': 'sigmoid'}   
4           0.1          rbf          {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}   
..          ...          ...                                              ...   
395       0.001      sigmoid   {'C': 20, 'gamma': 0.001, 'kernel': 'sigmoid'}   
396      0.0001          rbf      {'C': 20, 'gamma': 0.0001, 'kernel': 'rbf'}   
397      0.0001       linear   {'C': 20, 'gamma': 0.0001, 'kernel': 'linear'}   
398      0.0001         poly     {'C': 20, 'gamma': 0.0001, 'kernel': 'poly'}   
399      0.0001      sigmoid  {'C': 20, 'gamma': 0.0001, 'kernel': 'sigmoid'}   

     split0_test_score  split1_test_score  ...  split3_test_score  \
0             0.590909           0.761905  ...           0.619048   
1             0.818182           0.857143  ...           0.904762   
2             0.727273           0.809524  ...           0.714286   
3             0.681818           0.761905  ...           0.809524   
4             0.772727           0.904762  ...           0.952381   
..                 ...                ...  ...                ...   
395           0.727273           0.761905  ...           0.857143   
396           0.681818           0.761905  ...           0.857143   
397           0.863636           0.952381  ...           0.952381   
398           0.454545           0.476190  ...           0.523810   
399           0.454545           0.523810  ...           0.523810   

     split4_test_score  split5_test_score  split6_test_score  \
0             0.761905           0.619048           0.714286   
1             0.952381           0.761905           0.952381   
2             0.714286           0.761905           0.857143   
3             0.904762           0.619048           0.904762   
4             0.904762           0.714286           0.857143   
..                 ...                ...                ...   
395           0.857143           0.619048           0.809524   
396           0.809524           0.619048           0.761905   
397           1.000000           0.666667           0.952381   
398           0.523810           0.523810           0.523810   
399           0.523810           0.523810           0.523810   

     split7_test_score  split8_test_score  split9_test_score  mean_test_score  \
0             0.619048           0.761905           0.619048         0.673377   
1             0.857143           0.904762           0.857143         0.872294   
2             0.714286           0.952381           0.857143         0.787013   
3             0.666667           0.761905           0.571429         0.744372   
4             0.809524           0.857143           0.857143         0.853463   
..                 ... 

In [29]:
df_lr_grid[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0         1          rbf         0.673377
1         1       linear         0.872294
2         1         poly         0.787013
3         1      sigmoid         0.744372
4         1          rbf         0.853463
..      ...          ...              ...
395      20      sigmoid         0.787013
396      20          rbf         0.763420
397      20       linear         0.891126
398      20         poly         0.512121
399      20      sigmoid         0.516883

[400 rows x 3 columns]

In [30]:
print(GSCV_LR.best_score_)
gscv_lr_acc = GSCV_LR.best_score_
print(GSCV_LR.best_params_)

0.8577922077922077
{'C': 1.0, 'penalty': 'l1', 'solver': 'saga'}


In [31]:
grid_predictions = GSCV_LR.predict(x_test)
  
# print classification report
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.96      0.88      0.92        25
           1       0.57      0.50      0.53         8
           2       0.87      1.00      0.93        20

    accuracy                           0.87        53
   macro avg       0.80      0.79      0.79        53
weighted avg       0.87      0.87      0.86        53



In [32]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test, GSCV_LR.predict(x_test))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred_lr_grid = GSCV_LR.predict(x_test)
pred_prob = GSCV_LR.predict_proba(x_test)


cohen_score = cohen_kappa_score(y_test, Y_pred_lr_grid)
f1 = f1_score(y_test, Y_pred_lr_grid, average = "weighted")
precision = precision_score(y_test, Y_pred_lr_grid, average = "weighted")
recall = recall_score(y_test, Y_pred_lr_grid, average = "weighted")


auc_score = roc_auc_score(y_test, pred_prob, multi_class='ovr')

print(f"Precision  {precision}")
print(f"f1 Score  {f1}")
print(f"Recall  {recall}")
specificity = TNR
print("Specificity/TNR: " + str(TNR))

print("Cohen Kappa: " + str(cohen_score))
print(f"AUC Score  {auc_score}")

Precision  0.8655806867455761
f1 Score  0.863924235775925
Recall  0.8679245283018868
Specificity/TNR: 0.88
Cohen Kappa: 0.7840512223515717
AUC Score  0.9735714285714286


In [33]:
lr_performances_grid = [gscv_lr_acc, precision, recall, f1, cohen_score, auc_score ]
performance_dict_grid['LR'] = lr_performances_grid

performance_dict_grid

{'Metrics': ['Accuracy',
  'Precision',
  'Recall',
  'F1 Score',
  'Cohen Kappa',
  'AUC'],
 'SVC': [0.9101731601731602,
  0.9245283018867925,
  0.9245283018867925,
  0.9245283018867925,
  0.8767441860465116,
  0.987037037037037],
 'LR': [0.8577922077922077,
  0.8655806867455761,
  0.8679245283018868,
  0.863924235775925,
  0.7840512223515717,
  0.9735714285714286]}

# KNN Train, Test

In [34]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


modelKNN = KNeighborsClassifier() #, algorithm = 'ball_tree', weights = 'distance', metric = 'minkowski', p = 2
modelKNN.fit(x_train, y_train)
print(modelKNN.score(x_test, y_test))

# Predicting the Test set results
y_pred_knn = modelKNN.predict(x_test)
ac = accuracy_score(y_test, y_pred_knn)
print(accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

0.8113207547169812
0.8113207547169812
[[21  4  0]
 [ 2  4  2]
 [ 1  1 18]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86        25
           1       0.44      0.50      0.47         8
           2       0.90      0.90      0.90        20

    accuracy                           0.81        53
   macro avg       0.74      0.75      0.74        53
weighted avg       0.82      0.81      0.81        53



C:\Users\babar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [35]:
from sklearn.metrics import cohen_kappa_score
cmKNN = confusion_matrix(y_test, modelKNN.predict(x_test))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmKNN[1,1]  
TN = cmKNN[0,0] 
FP = cmKNN[0,1] 
FN = cmKNN[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalKNN = sum(sum(cmKNN))
Accuracy = (TN+TP)/totalKNN
# MCC
val = (TP * TN) - (FP * FN)
MCC_KNN = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred_knn = modelKNN.predict(x_test)
pred_prob = modelKNN.predict_proba(x_test)


cohen_score = cohen_kappa_score(y_test, Y_pred_knn)
f1 = f1_score(y_test, Y_pred_knn, average = "weighted")
precision = precision_score(y_test, Y_pred_knn, average = "weighted")
recall = recall_score(y_test, Y_pred_knn, average = "weighted")


auc_score = roc_auc_score(y_test, pred_prob, multi_class='ovr')

print(f"Precision  {precision}")
print(f"f1 Score  {f1}")
print(f"Recall  {recall}")
specificity = TNR
print("Specificity/TNR: " + str(TNR))

print("Cohen Kappa: " + str(cohen_score))
print(f"AUC Score  {auc_score}")


Precision  0.8194444444444444
f1 Score  0.8149674964325353
Recall  0.8113207547169812
Specificity/TNR: 0.84
Cohen Kappa: 0.6948762233736328
AUC Score  0.8957335257335256


In [36]:
# metrics = ["Accuracy", "Precision", "Recall", "F1 Score", "Specificity", "Cohen Kappa", "AUC"]
knn_performances = [ac, precision, recall, f1, cohen_score, auc_score ]
performance_dict['KNN'] = knn_performances

performance_dict

{'Metrics': ['Accuracy',
  'Precision',
  'Recall',
  'F1 Score',
  'Cohen Kappa',
  'AUC'],
 'SVC': [0.9245283018867925,
  0.9256220946130708,
  0.9245283018867925,
  0.920919486706486,
  0.8753674309229865,
  0.9799663299663299],
 'LR': [0.8301886792452831,
  0.8111635220125786,
  0.8301886792452831,
  0.8151632733842975,
  0.7175843694493783,
  0.9544083694083693],
 'KNN': [0.8113207547169812,
  0.8194444444444444,
  0.8113207547169812,
  0.8149674964325353,
  0.6948762233736328,
  0.8957335257335256]}

# Logistic Regression Hyperparameter Tuning GridSearchCV

In [ ]:
grid_params = { 'n_neighbors' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
               'weights' : ['uniform','distance'],
               'metric' : ['minkowski','euclidean','manhattan']}

GSCV_KNN = GridSearchCV(KNeighborsClassifier(), grid_params, verbose = 1, cv = 10, n_jobs = -1)
GSCV_KNN.fit(x_train, y_train)
GSCV_KNN.cv_results_

Fitting 10 folds for each of 120 candidates, totalling 1200 fits


In [ ]:
df_lr_grid = pd.DataFrame(GSCV_KNN.cv_results_)
df_lr_grid

In [ ]:
df_lr_grid[['param_metric', 'param_n_neighbors', 'mean_test_score']]

In [ ]:
print(GSCV_KNN.best_score_)
gscv_knn_acc = GSCV_KNN.best_score_
print(GSCV_KNN.best_params_)

In [ ]:
grid_predictions = GSCV_KNN.predict(x_test)
  
# print classification report
print(classification_report(y_test, grid_predictions))

In [ ]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test, GSCV_KNN.predict(x_test))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred_knn_grid = GSCV_KNN.predict(x_test)
pred_prob = GSCV_KNN.predict_proba(x_test)


cohen_score = cohen_kappa_score(y_test, Y_pred_knn_grid)
f1 = f1_score(y_test, Y_pred_knn_grid, average = "weighted")
precision = precision_score(y_test, Y_pred_knn_grid, average = "weighted")
recall = recall_score(y_test, Y_pred_knn_grid, average = "weighted")


auc_score = roc_auc_score(y_test, pred_prob, multi_class='ovr')

print(f"Precision  {precision}")
print(f"f1 Score  {f1}")
print(f"Recall  {recall}")
specificity = TNR
print("Specificity/TNR: " + str(TNR))

print("Cohen Kappa: " + str(cohen_score))
print(f"AUC Score  {auc_score}")

In [ ]:
knn_performances_grid = [gscv_knn_acc, precision, recall, f1, cohen_score, auc_score ]
performance_dict_grid['KNN'] = knn_performances_grid

performance_dict_grid

# Result of all classifiers

In [ ]:
performance_df = pd.DataFrame.from_dict(performance_dict)
performance_df


# Result of all classifiers after hyperparameter tuning 

In [ ]:
performance_df_grid = pd.DataFrame.from_dict(performance_dict_grid)
performance_df_grid

# Extracting Result

In [ ]:
performance_df = performance_df.transpose()
performance_df.to_csv("../Final CSV With YJ/With Yeo Johnson 80-20 Applying BFE Top 9 features.csv")

performance_df_grid = performance_df_grid.transpose()
performance_df_grid.to_csv("../Final CSV With YJ/With Yeo Johnson 80-20 Applying Hyperparameter BFE Top 9 features.csv")

# ROC Curve

In [ ]:
from sklearn.metrics import roc_curve

# predict probabilities
pred_prob1 = modelSVC.predict_proba(x_test)
pred_prob5 = modelLR.predict_proba(x_test)
pred_prob7 = modelKNN.predict_proba(x_test)

# roc curve for models
fpr1, tpr1, thresh1 = roc_curve(y_test, pred_prob1[:,1], pos_label = 1)
fpr5, tpr5, thresh5 = roc_curve(y_test, pred_prob5[:,1], pos_label = 1)
fpr7, tpr7, thresh7 = roc_curve(y_test, pred_prob7[:,1], pos_label = 1)

# roc curve for tpr = fpr 
random_probs = [0 for i in range(len(y_test))]
p_fpr, p_tpr, _ = roc_curve(y_test, random_probs, pos_label=1)

In [ ]:
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('seaborn')
sb.set_theme(style = 'whitegrid')

# plot roc curves
plt.plot(fpr1, tpr1, linestyle = '--', color = 'magenta', label = 'SVM')
plt.plot(fpr7, tpr7, linestyle = '--', color = 'cyan', label = 'KNN')
plt.plot(fpr5, tpr5, linestyle = '--', color = 'darkorange', label = 'LR')
plt.plot(p_fpr, p_tpr, linestyle = '--', color = 'cornflowerblue')
# title
plt.title('With Yeo Johnson 80-20 Applying BFE Top 9 Features')
# x label
plt.xlabel('False Positive Rate')
# y label
plt.ylabel('True Positive rate')

plt.legend(loc='best')
plt.savefig("../Final ROC With YJ/With Yeo Johnson 80-20 Applying BFE Top 9 Features.png", dpi=300)

plt.show();